// signed_url_test.go — Cross-language byte-identity gate.
// Loads `conformance/fixtures/signed_url_vectors.json` (generated by the Rust
// `UrlSigner` minter) and asserts, for each vector:
// 1. `CanonicalString(...)` output matches `canonical_string` byte-for-byte.
// 2. HMAC-SHA256(decoded_key, canonical) → base64url-nopad == `expected_sig_b64url_nopad`.
// 3. `UrlVerifier.Verify(...)` accepts the minted URL (current-key OR prev-key
// per vector.signed_by) and returns `AcceptedByPrevKey` matching signed_by.
// Plus five negative tests that exercise every `VerifyErr` kind the handler
// layer will need to map to 400/403.
// FAILURE SEMANTICS: a single vector failing means the Rust minter and the Go
// verifier have drifted — HALT execution and follow RECEIVED §F path 1
// (fix the Rust side, regenerate vectors, re-run conformance). DO NOT paper
// over in Go.
package main

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"
)

// vector mirrors `conformance/fixtures/signed_url_vectors.json` shape 1:1.
// Field names are JSON-tagged so schema drift in the Rust generator fails
// the test loudly (empty-string / zero values instead of silent tolerance).
type vector struct {
	Name              string `json:"name"`
	CanonicalString   string `json:"canonical_string"`
	Exp               uint64 `json:"exp"`
	ExpectedSigB64URL string `json:"expected_sig_b64url_nopad"`
	Kid               string `json:"kid"`
	SignedBy          string `json:"signed_by"` // "current" | "prev"
	SigningKeyB64     string `json:"signing_key_b64"`
	XorbHashHex       string `json:"xorb_hash_hex"`
	Range             *struct {
		Start        uint64 `json:"start"`
		EndInclusive uint64 `json:"end_inclusive"`
	} `json:"range"`
}

func loadVectors(t *testing.T) []vector {
	t.Helper()
	// Relative to `gateway/` (where `go test` runs); fixture lives at repo root.
	path := filepath.Join("..", "conformance", "fixtures", "signed_url_vectors.json")
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fixtures %q: %v", path, err)
	}
	var vs []vector
	if err := json.Unmarshal(b, &vs); err != nil {
		t.Fatalf("decode fixtures: %v", err)
	}
	if len(vs) == 0 {
		t.Fatal("fixtures file is empty — regenerate via cargo example")
	}
	return vs
}

// TestSignedURLVectors is the cross-language byte-identity gate. See file
// header for failure semantics.
func TestSignedURLVectors(t *testing.T) {
	vs := loadVectors(t)

	for _, v := range vs {
		v := v
		t.Run(v.Name, func(t *testing.T) {
			kid, err := uuid.Parse(v.Kid)
			if err != nil {
				t.Fatalf("parse kid: %v", err)
			}

			// Step 1: rebuild canonical string; MUST match byte-for-byte.
			var rng *[2]uint64
			if v.Range != nil {
				rng = &[2]uint64{v.Range.Start, v.Range.EndInclusive}
			}
			got := CanonicalString(CanonicalVersion, v.XorbHashHex, v.Exp, rng, kid)
			if got != v.CanonicalString {
				t.Fatalf("canonical string drift:\n  want %q\n  got  %q", v.CanonicalString, got)
			}

			// Step 2: HMAC + base64url-nopad; MUST match fixture sig.
			keyBytes, err := base64.StdEncoding.DecodeString(v.SigningKeyB64)
			if err != nil {
				t.Fatalf("decode signing_key_b64: %v", err)
			}
			if len(keyBytes) != SigningKeyLen {
				t.Fatalf("signing key length = %d, want %d", len(keyBytes), SigningKeyLen)
			}
			mac := hmac.New(sha256.New, keyBytes)
			mac.Write([]byte(got))
			sigB64 := base64.RawURLEncoding.EncodeToString(mac.Sum(nil))
			if sigB64 != v.ExpectedSigB64URL {
				t.Fatalf("sig drift:\n  want %s\n  got  %s", v.ExpectedSigB64URL, sigB64)
			}

			// Step 3: verifier round-trip — construct URL + parse + Verify.
			// For "current"-signed vectors we give the verifier the fixture key
			// as CURRENT. For "prev"-signed vectors we give the verifier an
			// UNRELATED current key + the fixture key as PREV, to prove both
			// rotation slots are consulted in the correct order.
			var curB64, prevB64 string
			switch v.SignedBy {
			case "current":
				curB64 = v.SigningKeyB64
			case "prev":
				// 32 bytes of zero != the fixture prev key, so current-path
				// must fall through.
				zeros := make([]byte, SigningKeyLen)
				curB64 = base64.StdEncoding.EncodeToString(zeros)
				prevB64 = v.SigningKeyB64
			default:
				t.Fatalf("unknown signed_by %q", v.SignedBy)
			}
			ver, err := NewUrlVerifier(curB64, prevB64, 7200)
			if err != nil {
				t.Fatalf("verifier init: %v", err)
			}

			// Build a realistic URL + query just like CAS minter would.
			q := url.Values{}
			q.Set("exp", formatUint(v.Exp))
			q.Set("kid", v.Kid)
			q.Set("sig", v.ExpectedSigB64URL)
			if v.Range != nil {
				q.Set("r", formatUint(v.Range.Start)+"-"+formatUint(v.Range.EndInclusive))
			}

			// Pin "now" to 1s BEFORE exp so the URL is valid.
			now := time.Unix(int64(v.Exp)-1, 0)
			ok, verr := ver.Verify(v.XorbHashHex, q, now)
			if verr != nil {
				t.Fatalf("Verify failed: %s", verr.Kind)
			}
			if ok.XorbHashHex != v.XorbHashHex {
				t.Fatalf("xorb hash drift: want %s got %s", v.XorbHashHex, ok.XorbHashHex)
			}
			if ok.Exp != v.Exp {
				t.Fatalf("exp drift: want %d got %d", v.Exp, ok.Exp)
			}
			if ok.Kid != kid {
				t.Fatalf("kid drift: want %s got %s", kid, ok.Kid)
			}
			wantAccByPrev := v.SignedBy == "prev"
			if ok.AcceptedByPrevKey != wantAccByPrev {
				t.Fatalf("accepted_by_prev_key mismatch: want %v got %v", wantAccByPrev, ok.AcceptedByPrevKey)
			}
			if (ok.Range == nil) != (v.Range == nil) {
				t.Fatalf("range nil-ness mismatch: want %v got %v", v.Range, ok.Range)
			}
			if v.Range != nil {
				if ok.Range[0] != v.Range.Start || ok.Range[1] != v.Range.EndInclusive {
					t.Fatalf("range mismatch: want %d-%d got %d-%d",
						v.Range.Start, v.Range.EndInclusive, ok.Range[0], ok.Range[1])
				}
			}
		})
	}
}

// TestSignedURLNegative exercises every VerifyErr.Kind value the handler
// layer must distinguish. These are NOT cross-language vectors — they pin the
// Go-side classification surface so refactors don't silently reclassify
// malformed-as-expired or vice versa.
func TestSignedURLNegative(t *testing.T) {
	vs := loadVectors(t)
	// Reuse the first "current"-signed vector as the positive baseline to mutate.
	var base *vector
	for i := range vs {
		if vs[i].SignedBy == "current" && vs[i].Range == nil {
			base = &vs[i]
			break
		}
	}
	if base == nil {
		t.Fatal("no current+no-range vector found in fixtures")
	}
	ver, err := NewUrlVerifier(base.SigningKeyB64, "", 7200)
	if err != nil {
		t.Fatalf("verifier init: %v", err)
	}
	validQuery := func() url.Values {
		q := url.Values{}
		q.Set("exp", formatUint(base.Exp))
		q.Set("kid", base.Kid)
		q.Set("sig", base.ExpectedSigB64URL)
		return q
	}
	validNow := time.Unix(int64(base.Exp)-1, 0)

	t.Run("tampered_sig", func(t *testing.T) {
		q := validQuery()
		sig := q.Get("sig")
		// Flip the last base64 char in a deterministic way (not '=' padded).
		last := sig[len(sig)-1]
		var flipped byte = 'A'
		if last == 'A' {
			flipped = 'B'
		}
		q.Set("sig", sig[:len(sig)-1]+string(flipped))
		_, verr := ver.Verify(base.XorbHashHex, q, validNow)
		if verr == nil || verr.Kind != "bad_signature" {
			t.Fatalf("want bad_signature, got %v", verr)
		}
	})

	t.Run("expired", func(t *testing.T) {
		_, verr := ver.Verify(base.XorbHashHex, validQuery(), time.Unix(int64(base.Exp)+1, 0))
		if verr == nil || verr.Kind != "expired" {
			t.Fatalf("want expired, got %v", verr)
		}
	})

	t.Run("missing_exp", func(t *testing.T) {
		q := validQuery()
		q.Del("exp")
		_, verr := ver.Verify(base.XorbHashHex, q, validNow)
		if verr == nil || verr.Kind != "malformed:exp" {
			t.Fatalf("want malformed:exp, got %v", verr)
		}
	})

	t.Run("malformed_range", func(t *testing.T) {
		q := validQuery()
		q.Set("r", "abc")
		_, verr := ver.Verify(base.XorbHashHex, q, validNow)
		if verr == nil || verr.Kind != "malformed:range" {
			t.Fatalf("want malformed:range, got %v", verr)
		}
	})

	t.Run("mixed_case_hex", func(t *testing.T) {
		mixed := strings.ToUpper(base.XorbHashHex[:4]) + base.XorbHashHex[4:]
		_, verr := ver.Verify(mixed, validQuery(), validNow)
		if verr == nil || verr.Kind != "malformed:xorb_hash_hex" {
			t.Fatalf("want malformed:xorb_hash_hex, got %v", verr)
		}
	})
}

// formatUint kept local so the test does not pull strconv imports inline.
func formatUint(x uint64) string {
	// strconv.FormatUint in base 10 — inlined here to keep the test file
	// import list symmetric with the production code.
	var buf [20]byte
	i := len(buf)
	if x == 0 {
		return "0"
	}
	for x > 0 {
		i--
		buf[i] = byte('0' + x%10)
		x /= 10
	}
	return string(buf[i:])
}
